// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: agenda.query.sql

package gendb

import (
	"context"
)

const archivePastEvents = `-- name: ArchivePastEvents :exec
UPDATE agenda_entry SET status = 5 WHERE date(enddate, '+1 day') < date('now') OR enddate=""
`

func (q *Queries) ArchivePastEvents(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, archivePastEvents)
	return err
}
