// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package gendb

import (
	"database/sql"
	"time"
)

type AgendaEntry struct {
	ID                   string
	Title                string
	Link                 string
	Price                sql.NullFloat64
	Address              string
	Startdate            string
	Description          string
	Infos                sql.NullString
	Poster               sql.NullString
	Category             sql.NullString
	Tag                  sql.NullString
	Place                sql.NullString
	Status               interface{}
	Starttime            interface{}
	Endtime              interface{}
	Subtitle             interface{}
	Enddate              interface{}
	Venuename            interface{}
	EventLifecycleStatus interface{}
	EventOwner           int64
}

type FormSubmission struct {
	ID                string
	Email             string
	Data              string
	EditToken         string
	CancelToken       string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Status            string
	ExpiredAt         time.Time
	ConfirmationToken string
}

type RefreshToken struct {
	ID        int64
	UserID    int64
	Token     string
	CreatedAt sql.NullTime
	ExpiresAt time.Time
}

type ScrapingTask struct {
	ID          int64
	Type        string
	Url         string
	Params      string
	RunningTime int64
	Status      sql.NullInt64
}

type User struct {
	ID           int64
	Username     string
	Password     string
	Role         sql.NullString
	Status       sql.NullInt64
	TokenVersion interface{}
}
