// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.query.sql

package gendb

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO user (username, password, status, role)
VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	Username string
	Password string
	Status   sql.NullInt64
	Role     sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Status,
		arg.Role,
	)
	return err
}
