CREATE TABLE IF NOT EXISTS scraping_task (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			type TEXT NOT NULL,
			url TEXT UNIQUE NOT NULL,
			params TEXT NOT NULL,
			running_time INTEGER NOT NULL,
			status INTEGER DEFAULT 0)